### ISSUE TITLE
Add puroses and tag definitions to the frontend

### ISSUE THREAD

**Issue by ciphersmaug** [PrivacyEngineering/hawk-monitor#3]
currently the hawk service has the possibility to store purposes for a mapping which is entirely missing from the frontend

**Comment by tomijange** [comment]
The api-specification of the hawk-service has no purpose-field (https://github.com/PrivacyEngineering/hawk-service/blob/81ab9d992a643c9843c9620c070bc0f77d3cebd6/openapi.json#L1089C8-L1089C27, https://github.com/PrivacyEngineering/hawk-service/blob/master/src/main/kotlin/org/datausagetracing/service/mapping/MappingPresentation.kt#L3)

**Comment by tomijange** [comment]
Added to backend in https://github.com/PrivacyEngineering/hawk-service/commit/b7771f39d88ba5ac3f2b3556b16f2ef4e1a72e55
Fixed in https://github.com/PrivacyEngineering/hawk-monitor/commit/ef61125ecb23eca2b4f9710cdfd7d498eac87330
